### ISSUE TITLE
Support of [tstzrange]

### ISSUE THREAD

**Issue by DarkGhostHunter** [belamov/postgres-range#11]
Currently PostgreSQL 12 supports `tstzrange`, which is _Range of timestamp with time zone_.

I _think_ implementation should be not an hassle since it's basically `tsrange` with timezone. Just two new letters. Even the official documentation names it only once.

**Comment by belamov** [comment]
yep, you are right, there is no any hassle with implementing this, apparently just missed or forgot about that type 

thanks for that catch!
