### ISSUE TITLE
DateRangeCast returns Carbon object with current date&time instead of null for [2020-08-31,)

### ISSUE THREAD

**Issue by matejjurancic** [belamov/postgres-range#12]
First of all thanks for this package, it is very useful.

**Describe the bug**
PHP: 7.4.9
PostgreSQL: 11.9 and 12.4
Laravel: 7.26.1

When from or to is set to null (e.g. `[2020-08-31,)`), some sort of default value is returned from RangeCast instance (e.g. Carbon object with current date&time).

**To Reproduce**
1. Create database column validity via migration
```php
$table->dateRange('validity');
```
2. Set casts in model
```php
protected $casts = ['validity' => DateRangeCast::class]
```
3. Store value in the database
```php
$model->update(['validity' => new DateRange(Carbon::parse('2020-08-31'), null)])
```
4. Fetch value from database
```php
$model->validity->to()
```

**Expected behavior**
I would expect to get `null` value from step 4, but I get Carbon object with current date&time.

**Additional context**
Similar result is with Integer or Float RangeCast. When from or to is set to null, 0 or 0.0 is returned.

On the other hand, this works as expected.
```php
$validity = new DateRange(Carbon::parse('2020-08-31'), null);
$validity->to(); // null
```

**Comment by belamov** [comment]
@matejjurancic thanks for detailed explanation, very nicely done, appreciate it
I'll look up into this!

**Comment by belamov** [comment]
@matejjurancic can you update package version to 1.0.3 in your project and confirm that everything is working as expected, please?

**Comment by matejjurancic** [comment]
I can confirm that everything works as expected in 1.0.3. I have tested DateRangeCast and FloatRangeCast.
