### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by mklein994** [belamov/postgres-range#19]
PHP 8 has been released: https://www.php.net/releases/8.0/en.php

[Laravel 8 supports it](https://github.com/laravel/framework/blob/c007d7cc726c5bf839d3547a5f021f927635ee73/composer.json#L18), so it would be great if this package could provide support for it as well.

I realize that it hasn't been out for very long, but it would be good to check if anything in this project is preventing support for PHP 8.

**Comment by belamov** [comment]
thanks for reminder!
all done, all tests are passing, update to 1.1.1
