### ISSUE TITLE
Query builder macro error with generated SQL

### ISSUE THREAD

**Issue by resohead** [belamov/postgres-range#7]
Cool package! I'm just starting to use PostgreSQL date ranges and thought I would try this out.

**Describe the bug**
Using the query builder macros throws an `operator is not unique` error. 

```php
App\Reservation::whereRangeOverlaps('during', $range)->get();
```
```
Ambiguous function: 7 ERROR:  operator is not unique: unknown && unknown
LINE 1: select * from "room_reservation" where $1 && $2
                                                  ^
HINT:  Could not choose a best candidate operator. 
You might need to add explicit type casts. (SQL: select * from "room_reservation" where during && [2010-01-07,2010-01-10))'
```

**To Reproduce**
Database: PostgreSQL 11.6
Laravel: 7.6.2
1. Create a table with a daterange field, e.g. during
2. Insert data to daterange field, e.g. [2010-01-01,2010-01-08)
3. Add to model to $protected casts, e.g. 'during' => DateRangeCast::class
4. Create a range to use in the query:
```php
$from = Carbon\Carbon::parse('2010-01-07');
$to = Carbon\Carbon::parse('2010-01-09');
$range = new DateRange($from, $to, '[', ']');
```
4. Run `whereRangeOverlaps('during', $range)->get();`
5. Expected the inserted row to be returned by the query.

I have not tried the other builder macros yet.

**Potential solution**
I think we can replace the `whereRaw` call with a standard `where` function. Laravel's grammar contains valid Postgres operators. Example, 
```php
Builder::macro(
    'whereRangeOverlaps',
    function ($left, $right) {
       //return $this->whereRaw('? && ?', [$left, $right]);
        return $this->where($left, '&&', $right);
    }
);
```

I will see how this works with the other macros, run some tests and try and submit a PR but I won't be able to do this right away.

Thanks!

**Comment by belamov** [comment]
Hey @resohead, thanks for describing this issue so detailed.

Can you please try to replace
```
App\Reservation::whereRangeOverlaps('during', $range)->get();
``` 
with
```
App\Reservation::whereRaw('during && ?', [$range . '::daterange'])->get();
``` 
and check if that's working as expected.

If so, I'll add explicit casts to all range objects

**Comment by resohead** [comment]
Thanks for the quick response. I am getting the following error
```
'SQLSTATE[22P02]: Invalid text representation: 7 ERROR:  malformed range literal: "[2010-01-07,2010-01-10)::daterange"
DETAIL:  Junk after right parenthesis or bracket. (SQL: select * from "room_reservation" where during && [2010-01-07,2010-01-10)::daterange)
```

But I think for this query to work I it needs to wrap the date range:

```sql
-- working
select * from "room_reservation" where during && '[2010-01-03,2010-01-04]'::daterange
```
instead of 
```sql
-- malformed range literal
select * from "room_reservation" where during && [2010-01-03,2010-01-04]::daterange
```

**Comment by belamov** [comment]
Yep, you're right, forgot quotes.

I'll create fix for this. Also will try out your suggestion about using `where` instead of `whereRaw`, but I think explicit type casting is a way to go.

Thanks!

**Comment by belamov** [comment]
Couldn't find a way to use PDO statements with these operators and types
Replaced all bindings to string extrapolation - it is much less secure, but I haven't got a clue how to make them work. Also added warning in documentation about this

If you have any ideas how to make them work - pr or new issue are welcome

**Comment by belamov** [comment]
created #9 issue where i described the problems I encountered with
